### ISSUE TITLE
Check $this->file is existed in class constructor

### ISSUE THREAD

**Issue by peter279k** [Jord-JD/uxdm-pdf-destination#1]
As title, please consider following code snippets:

```php
class PDFDestination
{
    public function __construct($file)
    {
        $this->file = $file;
    }
......
}
```

In class constructor, I think we should check the `$file` is existed.

**Comment by Jord-JD** [comment]
Thanks for the suggestion. 

However, this file will be created by this destination class. It is not supposed to exist at this point, and should be overwritten if it does.

**Comment by peter279k** [comment]
@DivineOmega, thank you for your reply.

And we need to consider following issues:

- If the specific file path exists invalid directory name, the `file_put_contents` will throw warning.
- The `file_get_contents` will always create/overwrite the contents.
Do we need to have the message to notice the file is created/overwritten?

**Comment by Jord-JD** [comment]
> If the specific file path exists invalid directory name, the file_put_contents will throw warning.

We should check that the directory exists, and then throw an exception. Good point. 

Feel free to make a PR for this if you wish.

> The file_get_contents will always create/overwrite the contents.
Do we need to have the message to notice the file is created/overwritten?

I think we can assume that if people specify the same file path, they want the file be overwritten.
